version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data:cached
    networks:
      - my_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      POSTGRES_DB: news_brevity_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - web_bundler_cache:/usr/local/bundle:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - my_network
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'

  telegram_bot:
    build:
      context: ./telegram_service
    volumes:
      - ./telegram_service:/app
    ports:
      - "5000:5000"
    networks:
      - my_network
    env_file:
      - '.env'

volumes:
  db_volume:
  web_bundler_cache:

networks:
  my_network:
    driver: bridge
